Homework #4. Task #2. Есин Максим (20.Б10-мм)
faf0be172/Kotlin_homeworks pull request #12
Opened 2021-03-25 19:16 UTC by faf0be172

2021-03-26 17:15 UTC, SpirinEgor requested changes
Надо обязательно от !! избавиться

2021-03-26 17:15 UTC, SpirinEgor commented on config/detekt/detekt.yml
> +    ignorePrivate: true
Лучше игнорировать override

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +class AVLNode <Key : Comparable<Key>, Value> (private var key: Key, private var value: Value) {
Почему ключ изменяемый? Кажется, что это инвариант для вершины.

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +        val leftSubtreeHeight = if (this.leftChild?.height != null) this.leftChild!!.height else 0
!! вообще нельзя использовать
Нужно аккуратно обрабатывать случаи с null

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +        val leftSubtreeHeight = if (this.leftChild?.height != null) this.leftChild!!.height else 0
И тут аналогично

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +        val leftSubtreeHeight = if (this.leftChild?.height != null) this.leftChild!!.height else 0
```
val leftSubtreeHeight = this.leftChild?.height ?: 0
```

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +        return when {
Если функция начинается с return, то красивее сделать через =
```
fun recursivePut(key: K, value: V): Value? =
    when {
         ...
```

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +                return if (this.leftChild != null) this.leftChild!!.recursiveContainsKey(key)
return в return как-то странно выглядит

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +    private val absoluteCriticalBalanceFactor = 2
Такое можно в companion object сложить

2021-03-26 17:15 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLTree.kt
> +class AVLTree <Key : Comparable<Key>, Value> {
Это же не реализует интерфейс Map

2021-03-27 16:04 UTC, faf0be172 commented on config/detekt/detekt.yml
> +    ignorePrivate: true
У меня в AVLNode нет override функций

2021-03-27 16:05 UTC, faf0be172 commented on src/main/kotlin/homework4/AVLNode.kt
> +class AVLNode <Key : Comparable<Key>, Value> (private var key: Key, private var value: Value) {
Тогда непонятно как удалять вершину в случае, когда мы находим самый левый элемент из правого поддерева

2021-03-28 14:48 UTC, SpirinEgor commented on config/detekt/detekt.yml
> +    ignorePrivate: true
Ага, если проблема из-за него, то надо подумать, как эту логику декомпозировать. Детект не так просто пишет комментарии -- тупое переписывание настроек не решение.

2021-03-28 14:50 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +class AVLNode <Key : Comparable<Key>, Value> (private var key: Key, private var value: Value) {
Переставлять вершину? Ну то есть ты вершину из листа перемещаешь на новое место. Если у тебя помимо ключа будет ещё какая-то информация хранится, то придётся все копировать. А если перемещать вершину целиком, то об этом заботиться не надо.

2021-03-28 14:56 UTC, SpirinEgor requested changes
По коду в целом ок. Можно пооптимизировать конструкции, более аккуратно реализовать. Ну и надо что-то с AVLNode сделать...

Вижу тесты на AVLTree, но не вижу на AVLNode. Хотя там тоже много функциональности.

Если есть вопросы -- быстрее в телеграмме спрашивать

2021-03-28 14:56 UTC, SpirinEgor commented on src/main/kotlin/homework4/AVLNode.kt
> +        }
```
private fun getSubTreeMin(): AVLNode<Key, Value> =
    this.leftChild?.let { getSubTreeMin } ?: this
```
В котлине много синтаксического сахара, надо пользоваться этим :)

2021-03-28 14:56 UTC, SpirinEgor commented on src/test/kotlin/homework4/AVLTreeTest.kt
> +    fun testRemoveFromEmptyMap() {
Котлин разрешает называть тесты какими-то фразами
```
fun `remove from empty map`() { ... }
```

2021-03-28 20:24 UTC, SpirinEgor approved these changes

2021-03-28 20:24 UTC, merged